name: Update Spec with Latest Basalt Commit

on:
  schedule:
    - cron: '0 0 * * *'  # Every day at 0:00 UTC
  workflow_dispatch:

jobs:
  update-spec:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repository
        uses: actions/checkout@v4

      - name: Fetch latest commit from basalt repo
        id: basalt
        run: |
          latest_commit=$(git ls-remote https://gitlab.freedesktop.org/mateosss/basalt.git HEAD | cut -f1)
          echo "commit=$latest_commit" >> "$GITHUB_OUTPUT"

      - name: Update Version field in spec file
        run: |
          sed -i 's|^%global commit .*|%global commit "${{ steps.get_commit.outputs.commit }}"|' *.spec
          echo "Updated spec file:"
          grep Version: *.spec

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git commit -am "Update spec Version to basalt commit ${{ steps.basalt.outputs.commit }}"
          git push
